version: "3.7"
services:
  vmangos_database:
    container_name: vmangos_database
    build:
      context: .
      args: 
      dockerfile: docker/database/Dockerfile
    restart: unless-stopped
#    ports:
#      - 3306:3306
    command: --max_allowed_packet=32505856
    volumes:
      - ./vol/backup:/vol/backup
      - ./vol/core_github:/vol/core_github
      - ./vol/database_github:/vol/database_github
      - ./vol/database:/var/lib/mysql
    environment:

  vmangos_realmd:
    container_name: vmangos_realmd
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/realmd/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    ports:
      - 3724:3724
    volumes:
      - ./vol/configuration/realmd.conf:/opt/vmangos/etc/realmd.conf:ro
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120

  vmangos_mangos:
    container_name: vmangos_mangos
    tty: true
    stdin_open: true
    ports:
      - 8085:8085
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/mangos/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    volumes:
      - ./vol/configuration/mangosd.conf:/opt/vmangos/etc/mangosd.conf:ro
      - ./vol/client_data_extracted/${VMANGOS_CLIENT}:/opt/vmangos/bin/${VMANGOS_CLIENT}:ro
      - ./vol/client_data_extracted/maps:/opt/vmangos/bin/maps:ro
      - ./vol/client_data_extracted/mmaps:/opt/vmangos/bin/mmaps:ro
      - ./vol/client_data_extracted/vmaps:/opt/vmangos/bin/vmaps:ro
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120

#  vmangos_yesilcms:
#    container_name: vmangos_yesilcms
#    tty: true
#    stdin_open: true
#    ports:
#      - 443:443
#    build:
#      context: .
#      args: 
#        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
#        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
#      dockerfile: docker/yesilcms/Dockerfile
#    depends_on:
#      - vmangos_database
#    restart: unless-stopped
#    volumes:
#    - ./vol/yesilcms_github:/var/www/html
#    environment:
#      - TZ=${TZ}
#      - WAIT_HOSTS=vmangos_database:3306
#      - WAIT_TIMEOUT=120
#      - MYSQL_ROOT_PASSWORD_YESILCMS=${MYSQL_ROOT_PASSWORD_YESILCMS}
