version: "3.7"
services:
  vmangos_database:
    container_name: vmangos_database
#    ports:
#      - 3306:3306
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/database/Dockerfile
    restart: unless-stopped
    command: --max_allowed_packet=32505856
    volumes:
      - ./volume/backup:/backup
      - ./volume/database:/opt/database
      - ./volume/core/sql:/opt/core/sql
    environment:
      - TZ=${TZ}
      - VMANGOS_WORLD_DATABASE=${VMANGOS_WORLD_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - VMANGOS_REALM_NAME=${VMANGOS_REALM_NAME}
      - VMANGOS_REALM_IP=${VMANGOS_REALM_IP}
      - VMANGOS_REALM_PORT=${VMANGOS_REALM_PORT}
      - VMANGOS_CLIENT=${VMANGOS_CLIENT}
      - VMANGOS_REALM_ICON=${VMANGOS_REALM_ICON}
      - VMANGOS_REALM_FLAGS=$VMANGOS_REALM_FLAGS{}
      - VMANGOS_TIMEZONE=${VMANGOS_TIMEZONE}
      - VMANGOS_ALLOWED_SECURITY_LEVEL=${VMANGOS_ALLOWED_SECURITY_LEVEL}
      - VMANGOS_POPULATION=${VMANGOS_POPULATION}
      - VMANGOS_GAMEBUILD_MIN=${VMANGOS_GAMEBUILD_MIN}
      - VMANGOS_GAMEBUILD_MAX=${VMANGOS_GAMEBUILD_MAX}
      - VMANGOS_FLAG=${VMANGOS_FLAG}

  vmangos_realmd:
    container_name: vmangos_realmd
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/realmd/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    ports:
      - 3724:3724
    volumes:
      - ./vol/configuration/realmd.conf:/opt/vmangos/etc/realmd.conf:ro
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120

  vmangos_mangos:
    container_name: vmangos_mangos
    tty: true
    stdin_open: true
    ports:
      - 8085:8085
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/mangos/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    volumes:
      - ./vol/configuration/mangosd.conf:/opt/vmangos/etc/mangosd.conf:ro
      - ./vol/server_data/${VMANGOS_CLIENT}:/opt/vmangos/bin/${VMANGOS_CLIENT}:ro
      - ./vol/server_data/maps:/opt/vmangos/bin/maps:ro
      - ./vol/server_data/mmaps:/opt/vmangos/bin/mmaps:ro
      - ./vol/server_data/vmaps:/opt/vmangos/bin/vmaps:ro
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120
