version: "3.7"

networks:
   vmangos-network:
     external: true

services:
  vmangos_database:
    container_name: vmangos_database
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.vmangos_database.rule=HostSNI(`*`)"
      - "traefik.tcp.services.vmangos_database.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.vmangos_database.entrypoints=mysql"

    build:
      context: .
      dockerfile: docker/database/Dockerfile
    restart: unless-stopped
    command: --max_allowed_packet=32505856
    volumes:
      - ./vol/backup:/vol/backup
      - ./vol/core_github:/vol/core_github
      - ./vol/database_github:/vol/database_github
      - ./vol/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - VMANGOS_WORLD_DATABASE=${VMANGOS_WORLD_DATABASE}
      - VMANGOS_REALM_NAME=${VMANGOS_REALM_NAME}
      - VMANGOS_REALM_IP=${VMANGOS_REALM_IP}
      - VMANGOS_REALM_PORT=${VMANGOS_REALM_PORT}
      - VMANGOS_REALM_ICON=${VMANGOS_REALM_ICON}
      - VMANGOS_REALM_FLAGS=${VMANGOS_REALM_FLAGS}
      - VMANGOS_TIMEZONE=${VMANGOS_TIMEZONE}
      - VMANGOS_ALLOWED_SECURITY_LEVEL=${VMANGOS_ALLOWED_SECURITY_LEVEL}
      - VMANGOS_POPULATION=${VMANGOS_POPULATION}
      - VMANGOS_GAMEBUILD_MIN=${VMANGOS_GAMEBUILD_MIN}
      - VMANGOS_GAMEBUILD_MAX=${VMANGOS_GAMEBUILD_MAX}
      - VMANGOS_FLAG=${VMANGOS_FLAG}
    networks:
      - vmangos-network

  vmangos_realmd:
    container_name: vmangos_realmd
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.vmangos_realmd.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.vmangos_realmd.entrypoints=vmangos_realmd"
      - "traefik.tcp.services.vmangos_realmd.loadbalancer.server.port=3724"
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/realmd/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    volumes:
      - ./vol/configuration/realmd.conf:/opt/vmangos/etc/realmd.conf:ro
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120
    networks:
      - vmangos-network

  vmangos_mangos:
    container_name: vmangos_mangos
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.vmangos_mangos.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.vmangos_mangos.entrypoints=vmangos_mangos"
      - "traefik.tcp.services.vmangos_mangos.loadbalancer.server.port=8085"
    tty: true
    stdin_open: true
    build:
      context: .
      args: 
        - VMANGOS_USER_ID=${VMANGOS_USER_ID}
        - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
      dockerfile: docker/mangos/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    volumes:
      - ./vol/configuration/mangosd.conf:/opt/vmangos/etc/mangosd.conf:ro
      - ./vol/client_data_extracted/${VMANGOS_CLIENT}:/opt/vmangos/bin/${VMANGOS_CLIENT}:ro
      - ./vol/client_data_extracted/maps:/opt/vmangos/bin/maps:ro
      - ./vol/client_data_extracted/mmaps:/opt/vmangos/bin/mmaps:ro
      - ./vol/client_data_extracted/vmaps:/opt/vmangos/bin/vmaps:ro
    environment:
      - TZ=${TZ}
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120
    networks:
      - vmangos-network
