services:
  vmangos_database:
    container_name: vmangos_database
#    ports:
#      - 3306:3306
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    restart: unless-stopped
    command: --max_allowed_packet=32505856
    volumes:
      - vmangos_database:/var/lib/mysql
      - ./vmangos/sql:/opt/vmangos/sql
      - ./database:/opt/database
      - ./world_database:/opt/world_database
      - ./backup:/backup
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - VMANGOS_WORLD=${VMANGOS_WORLD}
      - VMANGOS_REALM_NAME=${VMANGOS_REALM_NAME}
      - VMANGOS_REALM_IP=${VMANGOS_REALM_IP}
      - VMANGOS_REALM_PORT=${VMANGOS_REALM_PORT}
      - VMANGOS_REALM_ICON=${VMANGOS_REALM_ICON}
      - VMANGOS_REALM_FLAGS=${VMANGOS_REALM_FLAGS}
      - VMANGOS_TIMEZONE=${VMANGOS_TIMEZONE}
      - VMANGOS_ALLOWED_SECURITY_LEVEL=${VMANGOS_ALLOWED_SECURITY_LEVEL}
      - VMANGOS_POPULATION=${VMANGOS_POPULATION}
      - VMANGOS_GAMEBUILD_MIN=${VMANGOS_GAMEBUILD_MIN}
      - VMANGOS_GAMEBUILD_MAX=${MANGOS_GAMEBUILD_MAX}
      - VMANGOS_FLAG=${VMANGOS_FLAG}

  vmangos_realmd:
    container_name: vmangos_realmd
    build:
      context: .
      dockerfile: docker/realmd/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    ports:
      - 3724:3724
    volumes:
      - ./config/realmd.conf:/opt/vmangos/etc/realmd.conf:ro
    environment:
      - TZ=Etc/UTC
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120
      - VMANGOS_USER_ID=${VMANGOS_USER_ID}
      - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}

  vmangos_mangos:
    container_name: vmangos_mangos
    tty: true
    stdin_open: true
    ports:
      - 8085:8085
    build:
      context: .
      dockerfile: docker/mangos/Dockerfile
    depends_on:
      - vmangos_database
    restart: unless-stopped
    volumes:
      - ./config/mangosd.conf:/opt/vmangos/etc/mangosd.conf:ro
      - ./src/data/5875:/opt/vmangos/bin/5875:ro
      - ./src/data/maps:/opt/vmangos/bin/maps:ro
      - ./src/data/mmaps:/opt/vmangos/bin/mmaps:ro
      - ./src/data/vmaps:/opt/vmangos/bin/vmaps:ro
    environment:
      - TZ=Etc/UTC
      - WAIT_HOSTS=vmangos_database:3306
      - WAIT_TIMEOUT=120
      - VMANGOS_USER_ID=${VMANGOS_USER_ID}
      - VMANGOS_GROUP_ID=${VMANGOS_GROUP_ID}
